#!/usr/bin/env bash

# Check if an IP address was passed as an argument
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi

# Store the IP address from the argument
IP_ADDRESS=$1

# Ping the provided IP address 5 times
ping -c 5 "$IP_ADDRESS"
